### ISSUE TITLE
自学计算机科学方面的朋友们，过来分享下CS 路程吧。

### ISSUE THREAD

**Issue by baozhixue** [codefollower/My-Blog#12]
这阵子在自学Python，感觉有些迷茫。
比如我在这段时间需要读写什么书籍（中英文都可以），或者还需要做些什么可以达到CS专业毕业的学生的水平。

比如你可以分享一下你的学习过程，或者在自学过程中遇到的最大难题。
谢谢！

因为英语现在还是有点渣，所以就直接发中文的了。

我的邮箱是zhixuebao@outlook.com。

谢谢！

**Comment by lerencao** [comment]
But why post here on other people's blog?

**Comment by baozhixue** [comment]
你好。
我是第一次使用Github，所以有些东西暂时不懂。
所以，造成了此次的情况。
